INBOX_COLLECTION = "bus_inbox"
BINDINGS_COLLECTION = "bus_bindings"

STATUS_PENDING = "Pending"
STATUS_PROCESSED = "Processed"
STATUS_DEAD = "Dead"

SPEC_VERSION = "1.0"
DEFAULT_SOURCE = "urn:mongobus:unknown"
CLAIM_CHECK_CONTENT_TYPE = "application/vnd.mongobus.claim-check+json"

DEFAULT_LOCK_SECONDS = 60
DEFAULT_MAX_ATTEMPTS = 10
DEFAULT_POLL_SECONDS = 0.05
